"""
app/redis_client.py
===================
Redis connection factory, crawl-scoped key functions, and concurrency
semaphore helpers.

All Redis keys are generated by functions parameterized by ``crawl_id``
so that multiple simultaneous crawl runs never share state.
"""

from __future__ import annotations

from typing import Optional

import redis.asyncio as aioredis

from app.config import settings

# ---------------------------------------------------------------------------
# Crawl-scoped key functions
# ---------------------------------------------------------------------------


def tasks_key(crawl_id: str) -> str:
    """Redis stream key for pending crawl tasks."""
    return f"crawl:{crawl_id}:stream:audit_tasks"


def results_key(crawl_id: str) -> str:
    """Redis stream key for extraction results."""
    return f"crawl:{crawl_id}:stream:audit_results"


def telemetry_key(crawl_id: str) -> str:
    """Redis stream key for link drop telemetry events."""
    return f"crawl:{crawl_id}:stream:dropped_telemetry"


def dlq_key(crawl_id: str) -> str:
    """Redis stream key for the Dead Letter Queue."""
    return f"crawl:{crawl_id}:stream:dlq"


def visited_key(crawl_id: str) -> str:
    """Redis set key tracking successfully processed URL fingerprints."""
    return f"crawl:{crawl_id}:set:visited_fingerprints"


def queued_key(crawl_id: str) -> str:
    """Redis set key tracking discovered (queued) URL fingerprints."""
    return f"crawl:{crawl_id}:set:queued_fingerprints"


def budget_key(crawl_id: str) -> str:
    """Redis counter key for the global page budget."""
    return f"crawl:{crawl_id}:budget:tickets_dispensed"


def lock_key(crawl_id: str, fingerprint: str) -> str:
    """Redis key for an in-flight processing lock on a single URL."""
    return f"crawl:{crawl_id}:lock:processing:{fingerprint}"


def domain_throttle_key(crawl_id: str, domain: str) -> str:
    """Redis counter key for per-domain concurrency throttling."""
    return f"crawl:{crawl_id}:throttle:domain:{domain}"


def consumer_group_name(crawl_id: str) -> str:
    """Consumer group name scoped to a crawl."""
    return f"audit_workers:{crawl_id}"


# ---------------------------------------------------------------------------
# Backward-compatible constants (used internally only)
# ---------------------------------------------------------------------------

# Read from settings at module load — values used by callers that have not
# yet been migrated to key functions.
PEL_TIMEOUT_MS: int = settings.PEL_TIMEOUT_MS
MAX_RETRIES: int = settings.MAX_RETRIES
MAX_DEPTH: int = settings.MAX_DEPTH
MAX_PAGES_PER_RUN: int = settings.MAX_PAGES_PER_RUN
MAX_CONCURRENT_PER_DOMAIN: int = settings.MAX_CONCURRENT_PER_DOMAIN

_DOMAIN_SLOT_TTL_S: int = 90

# ---------------------------------------------------------------------------
# Lua scripts (atomic Redis operations)
# ---------------------------------------------------------------------------

#: Atomically increment the budget counter and reject if the limit is reached.
#: KEYS[1] = budget_key, ARGV[1] = limit
#: Returns the new ticket number on success, or 0 if the limit was exceeded.
_LUA_RESERVE_TICKET = """
local key   = KEYS[1]
local limit = tonumber(ARGV[1])
local new   = redis.call('INCR', key)
if new > limit then
    redis.call('DECR', key)
    return 0
end
return new
"""

#: Atomically acquire one domain concurrency slot.
#: KEYS[1] = domain_throttle_key, ARGV[1] = max_slots, ARGV[2] = ttl_seconds
#: Returns 1 if acquired, 0 if at capacity.
_LUA_ACQUIRE_SLOT = """
local key      = KEYS[1]
local max_slots = tonumber(ARGV[1])
local ttl      = tonumber(ARGV[2])
local current  = redis.call('INCR', key)
if current > max_slots then
    redis.call('DECR', key)
    return 0
end
redis.call('EXPIRE', key, ttl)
return 1
"""


# ---------------------------------------------------------------------------
# Connection factory
# ---------------------------------------------------------------------------


def create_redis_pool(
    url: Optional[str] = None,
    max_connections: int = 20,
    decode_responses: bool = True,
) -> aioredis.Redis:
    """
    Create and return an async Redis connection pool.

    Parameters
    ----------
    url:
        Redis connection URL.  Defaults to ``settings.REDIS_URL``.
    max_connections:
        Pool size.  Size to (num_workers × pipeline_depth).
    decode_responses:
        When ``True``, Redis returns ``str`` instead of ``bytes``.
    """
    target_url = url or settings.REDIS_URL
    pool = aioredis.ConnectionPool.from_url(
        target_url,
        max_connections=max_connections,
        decode_responses=decode_responses,
    )
    return aioredis.Redis(connection_pool=pool, socket_timeout=10.0)


# ---------------------------------------------------------------------------
# Consumer group bootstrap
# ---------------------------------------------------------------------------


def persist_consumer_group_name(crawl_id: str) -> str:
    """Consumer group name for the persistence consumer."""
    return f"audit_persist:{crawl_id}"


async def ensure_consumer_group(redis: aioredis.Redis, crawl_id: str) -> None:
    """
    Idempotently create the worker consumer group for a crawl.

    Uses ``MKSTREAM`` so the stream is created if it does not yet exist.
    The ``BUSYGROUP`` error is swallowed — safe to call at every worker startup.

    Parameters
    ----------
    redis:
        An active async Redis client.
    crawl_id:
        The crawl namespace identifier.
    """
    try:
        await redis.xgroup_create(
            name=tasks_key(crawl_id),
            groupname=consumer_group_name(crawl_id),
            id="$",
            mkstream=True,
        )
    except aioredis.ResponseError as exc:
        if "BUSYGROUP" in str(exc):
            pass
        else:
            raise


async def ensure_persist_consumer_groups(redis: aioredis.Redis, crawl_id: str) -> None:
    """
    Idempotently create persistence consumer groups for results, telemetry, and DLQ streams.
    """
    group = persist_consumer_group_name(crawl_id)
    streams = [results_key(crawl_id), telemetry_key(crawl_id), dlq_key(crawl_id)]
    for stream in streams:
        try:
            await redis.xgroup_create(
                name=stream,
                groupname=group,
                id="0",
                mkstream=True,
            )
        except aioredis.ResponseError as exc:
            if "BUSYGROUP" in str(exc):
                pass
            else:
                raise


# ---------------------------------------------------------------------------
# Domain concurrency semaphore
# ---------------------------------------------------------------------------


async def acquire_domain_slot(
    redis: aioredis.Redis,
    crawl_id: str,
    domain: str,
) -> bool:
    """
    Atomically attempt to acquire one concurrency slot for ``domain``.

    Uses a Lua script to guarantee the increment, threshold check, and TTL
    assignment happen as a single atomic operation with no crash window.

    Parameters
    ----------
    redis:
        An active async Redis client.
    crawl_id:
        The crawl namespace identifier.
    domain:
        Target domain (e.g. ``"example.com"``).

    Returns
    -------
    bool
        ``True`` if the slot was granted; ``False`` if the domain is at capacity.
    """
    if MAX_CONCURRENT_PER_DOMAIN <= 0:
        return True

    result: int = await redis.eval(
        _LUA_ACQUIRE_SLOT,
        1,
        domain_throttle_key(crawl_id, domain),
        MAX_CONCURRENT_PER_DOMAIN,
        _DOMAIN_SLOT_TTL_S,
    )
    return bool(result)


async def release_domain_slot(
    redis: aioredis.Redis,
    crawl_id: str,
    domain: str,
) -> None:
    """
    Release one concurrency slot for ``domain``.

    Decrements the counter and deletes the key when it reaches zero.
    Resets the TTL while peers are still holding slots.

    Parameters
    ----------
    redis:
        An active async Redis client.
    crawl_id:
        The crawl namespace identifier.
    domain:
        Target domain.
    """
    if MAX_CONCURRENT_PER_DOMAIN <= 0:
        return

    key = domain_throttle_key(crawl_id, domain)
    remaining: int = await redis.decr(key)
    if remaining <= 0:
        await redis.delete(key)
    else:
        await redis.expire(key, _DOMAIN_SLOT_TTL_S)


async def reserve_page_ticket(
    redis: aioredis.Redis,
    crawl_id: str,
    global_max_pages: int,
) -> int:
    """
    Atomically reserve a global budget ticket for one page.

    Uses a Lua script to guarantee increment and threshold check happen as
    a single atomic operation — no two workers can simultaneously read the
    same count and both pass the budget gate.

    Parameters
    ----------
    redis:
        An active async Redis client.
    crawl_id:
        The crawl namespace identifier.
    global_max_pages:
        The configured page budget ceiling.

    Returns
    -------
    int
        The assigned ticket number (>= 1) if granted, or ``0`` if the budget
        is exhausted.
    """
    if global_max_pages <= 0:
        return 1  # Budget disabled — always grant

    result: int = await redis.eval(
        _LUA_RESERVE_TICKET,
        1,
        budget_key(crawl_id),
        global_max_pages,
    )
    return int(result)
